name: Docker

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml
  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: GHCR login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/vanutp/tiktok2telegram:latest
      - name: Deploy
        env:
          UPDATE_POST_KEY: ${{ secrets.UPDATE_POST_KEY }}
        run: |
          curl --request POST \
               --url https://vhap-update.vanutp.dev/update \
               --header "Content-Type: application/json" \
               --data '{"key":"'$UPDATE_POST_KEY'"}' \
               --fail
